// lib/autopilot/types.ts
// Phase 5: Hive Autopilot - Type definitions
//
// Core types for the autonomous strategy engine

import type { DomainName } from '../contextGraph/companyContextGraph';

// ============================================================================
// Autonomy & Governance Types
// ============================================================================

/**
 * Autonomy level controls how aggressive Autopilot is
 */
export type AutonomyLevel =
  | 'manual_only'      // Only suggestions, no automation
  | 'ai_assisted'      // Suggestions + diagnostics
  | 'semi_autonomous'  // Auto-budget + auto-creative safe changes
  | 'full_autonomous'; // Full cycle updates + write-through

/**
 * Autopilot configuration for a company
 */
export interface AutopilotConfig {
  companyId: string;
  enabled: boolean;
  autonomyLevel: AutonomyLevel;
  cycleFrequency: 'daily' | 'weekly' | 'bi_weekly';
  allowedDomains: DomainName[];
  budgetFlexibility: number; // 0-1, how much budget can shift
  experimentBudgetPercent: number; // % of budget for experiments
  riskTolerance: 'conservative' | 'moderate' | 'aggressive';
  requireApprovalFor: ('budget' | 'creative' | 'audience' | 'channel')[];
  notifyOnChanges: boolean;
  emergencyStopThreshold: number; // Performance drop % to trigger stop
  lastCycleAt?: string;
  createdAt: string;
  updatedAt: string;
}

// ============================================================================
// Hypothesis Types
// ============================================================================

/**
 * A hypothesis generated by the system
 */
export interface Hypothesis {
  id: string;
  companyId: string;
  hypothesis: string;
  domain: 'media' | 'creative' | 'audience' | 'seo' | 'content' | 'brand';
  category: HypothesisCategory;
  requiredData: string[];
  missingData: string[];
  dataCompleteness: number; // 0-1
  expectedImpact: number; // 0-1 normalized
  confidence: number; // 0-1
  reasoning: string;
  supportingEvidence: string[];
  risks: string[];
  suggestedExperiment?: ExperimentPlan;
  status: 'pending' | 'testing' | 'validated' | 'invalidated' | 'skipped';
  generatedAt: string;
  validatedAt?: string;
  validationResult?: HypothesisValidation;
}

export type HypothesisCategory =
  | 'budget_reallocation'
  | 'channel_expansion'
  | 'channel_reduction'
  | 'creative_refresh'
  | 'audience_refinement'
  | 'geo_targeting'
  | 'seasonal_adjustment'
  | 'competitive_response'
  | 'performance_optimization'
  | 'brand_alignment'
  | 'funnel_optimization';

export interface HypothesisValidation {
  validated: boolean;
  actualImpact: number;
  expectedImpact: number;
  variance: number;
  learnings: string[];
  shouldContinue: boolean;
}

// ============================================================================
// Experiment Types
// ============================================================================

/**
 * An experiment plan derived from a hypothesis
 */
export interface ExperimentPlan {
  id: string;
  companyId: string;
  name: string;
  hypothesisId: string;
  type: ExperimentType;
  description: string;

  // Scope
  channels: string[];
  geos?: string[];
  audiences?: string[];

  // Changes
  budgetChange?: BudgetChange;
  targetingChange?: TargetingChange;
  creativeTestCells?: CreativeTestCell[];
  biddingChange?: BiddingChange;

  // Expectations
  expectedLift: number; // Percentage
  minDetectableEffect: number;
  statisticalPower: number;

  // Timeline
  duration: number; // Days
  startDate?: string;
  endDate?: string;

  // Metrics
  metrics: {
    primary: string;
    secondary: string[];
    guardrails: string[];
  };

  // Status
  status: 'draft' | 'approved' | 'running' | 'paused' | 'completed' | 'cancelled';
  results?: ExperimentResults;

  createdAt: string;
  updatedAt: string;
}

export type ExperimentType =
  | 'budget_test'
  | 'channel_test'
  | 'creative_test'
  | 'audience_test'
  | 'geo_test'
  | 'bidding_test'
  | 'landing_page_test';

export interface BudgetChange {
  type: 'increase' | 'decrease' | 'reallocation';
  channels: Record<string, { current: number; proposed: number }>;
  totalDelta: number;
}

export interface TargetingChange {
  type: 'add' | 'remove' | 'modify';
  segments: string[];
  geos?: string[];
  demographics?: Record<string, unknown>;
}

export interface CreativeTestCell {
  id: string;
  name: string;
  variant: string;
  allocation: number; // Percentage
  creative: {
    format: string;
    angle: string;
    hook?: string;
    cta?: string;
  };
}

export interface BiddingChange {
  strategy: string;
  targetCpa?: number;
  targetRoas?: number;
  maxCpc?: number;
}

export interface ExperimentResults {
  completedAt: string;
  winner?: string;
  lift: number;
  confidence: number;
  primaryMetric: {
    control: number;
    treatment: number;
    lift: number;
    pValue: number;
  };
  secondaryMetrics: Record<string, {
    control: number;
    treatment: number;
    lift: number;
  }>;
  recommendations: string[];
  shouldScale: boolean;
}

// ============================================================================
// Budget Allocation Types
// ============================================================================

/**
 * Budget allocation output
 */
export interface BudgetAllocation {
  companyId: string;
  period: 'monthly' | 'quarterly';
  totalBudget: number;

  // Channel allocation
  channels: {
    search: number;
    social: number;
    display: number;
    video: number;
    lsa: number;
    audio: number;
    ooh: number;
    affiliate: number;
    email: number;
    other: number;
  };

  // Allocation rationale
  rationale: Record<string, string>;

  // Performance predictions
  predictions: {
    expectedConversions: number;
    expectedRevenue: number;
    expectedRoas: number;
    expectedCpa: number;
  };

  // Confidence
  confidence: number;

  // Comparison to current
  vsCurrentAllocation: Record<string, {
    current: number;
    proposed: number;
    delta: number;
    reason: string;
  }>;

  generatedAt: string;
}

// ============================================================================
// Creative Optimization Types
// ============================================================================

/**
 * Creative optimization recommendations
 */
export interface CreativeRecommendation {
  id: string;
  companyId: string;
  type: 'angle' | 'format' | 'hook' | 'cta' | 'script' | 'visual';
  platform: string;
  audience?: string;

  recommendation: string;
  reasoning: string;

  // Performance basis
  basedOn: {
    topPerformers: string[];
    underperformers: string[];
    marketTrends: string[];
    competitorInsights: string[];
  };

  expectedImpact: number;
  confidence: number;
  priority: 'high' | 'medium' | 'low';

  // Implementation
  suggestedCopy?: string;
  suggestedVisual?: string;
  suggestedFormat?: string;

  status: 'pending' | 'approved' | 'implemented' | 'rejected';
  generatedAt: string;
}

// ============================================================================
// Signal & Alert Types
// ============================================================================

/**
 * A signal detected by the monitor
 */
export interface Signal {
  id: string;
  companyId: string;
  type: SignalType;
  category: SignalCategory;
  severity: SignalSeverity;

  title: string;
  description: string;

  // Context
  metric: string;
  currentValue: number;
  previousValue: number;
  changePercent: number;
  threshold: number;

  // Source
  channel?: string;
  campaign?: string;

  // Actions
  suggestedActions: string[];
  autoActionTaken?: string;

  // Status
  status: 'active' | 'acknowledged' | 'resolved' | 'ignored';
  acknowledgedBy?: string;
  acknowledgedAt?: string;
  resolvedAt?: string;
  resolution?: string;

  detectedAt: string;
}

export type SignalSeverity = 'info' | 'warning' | 'critical';

export type SignalCategory =
  | 'performance'
  | 'financial'
  | 'budget'
  | 'technical'
  | 'competitive'
  | 'seasonal'
  | 'data_quality'
  | 'strategic';

export type SignalType =
  | 'cpa_spike'
  | 'ctr_collapse'
  | 'conversion_drop'
  | 'budget_exhaustion'
  | 'tracking_failure'
  | 'negative_roi'
  | 'roas_decline'
  | 'call_volume_drop'
  | 'form_submission_drop'
  | 'seasonal_anomaly'
  | 'competitive_threat'
  | 'quality_score_drop'
  | 'impression_share_loss'
  | 'context_gap'
  | 'strategy_misalignment';

/**
 * Signal threshold configuration
 */
export interface SignalThresholds {
  [key: string]: {
    warning: number;
    critical: number;
    lookbackDays: number;
  };
}

/**
 * Alert configuration for a company
 */
export interface AlertConfig {
  enabled: boolean;
  minSeverity?: SignalSeverity;
  enabledTypes?: SignalType[];
  quietHours?: {
    start: number; // Hour 0-23
    end: number;
  };
  channels?: {
    email?: boolean;
    slack?: boolean;
    webhook?: string;
  };
}

// ============================================================================
// Quarterly Planning Types
// ============================================================================

/**
 * A quarterly strategic plan
 */
export interface QuarterlyPlan {
  id: string;
  companyId: string;
  quarter: string; // e.g., "Q1 2025"
  startDate: string;
  endDate: string;
  status: 'draft' | 'review' | 'approved' | 'active' | 'completed';

  // Executive Summary
  executiveSummary: string;

  // Budget
  totalBudget: number;
  weeklyBudgets: WeeklyBudget[];
  channelStrategies: ChannelStrategy[];

  // Creative
  creativeRoadmap: CreativeRoadmap;
  messagingPriorities: string[];
  geoTargets: string[];

  // Performance
  kpis: QuarterlyKPI[];
  expectedImpact: {
    revenue: { min: number; expected: number; max: number };
    conversions: { min: number; expected: number; max: number };
    efficiency: { cpa: number; roas: number };
  };

  // Risk Management
  risks: RiskAssessment[];
  milestones: Milestone[];

  // Context
  constraints: string[];
  assumptions: string[];

  // Versioning
  previousPlanId?: string;

  // Metadata
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  approvedBy?: string;
  approvedAt?: string;
}

/**
 * Weekly budget distribution
 */
export interface WeeklyBudget {
  week: number;
  startDate: string;
  endDate: string;
  totalBudget: number;
  channelBudgets: Record<string, number>;
  notes?: string;
  adjustmentReason?: string;
}

/**
 * Channel-specific strategy
 */
export interface ChannelStrategy {
  channel: string;
  allocation: number; // Percentage
  quarterlyBudget: number;
  monthlyBudget: number;
  objectives: string[];
  tactics: string[];
  targetMetrics: Record<string, number>;
  priority: 'high' | 'medium' | 'low';
  status: 'planned' | 'active' | 'paused' | 'completed';
}

/**
 * Creative roadmap for the quarter
 */
export interface CreativeRoadmap {
  themes: string[];
  formats: Record<string, string[]>; // channel -> formats
  refreshSchedule: Array<{ week: number; action: string }>;
  testingPlan: Array<{ test: string; channel: string; duration: string }>;
  productionNeeds: string[];
}

/**
 * Quarterly KPI
 */
export interface QuarterlyKPI {
  metric: string;
  target: number;
  unit: string;
  baseline: number;
  stretch: number;
  priority: 'high' | 'medium' | 'low';
  measurementMethod: string;
}

/**
 * Risk assessment
 */
export interface RiskAssessment {
  id: string;
  category: 'budget' | 'creative' | 'competitive' | 'external' | 'technical';
  title: string;
  description: string;
  likelihood: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  mitigation: string;
  owner: string;
}

/**
 * Quarterly milestone
 */
export interface Milestone {
  id: string;
  week: number;
  date: string;
  title: string;
  description: string;
  criteria: string[];
  status: 'pending' | 'in_progress' | 'completed' | 'missed';
}

// ============================================================================
// Cycle & Log Types
// ============================================================================

/**
 * Result of an autopilot cycle
 */
export interface CycleResult {
  id: string;
  companyId: string;
  cycleNumber: number;

  // Timing
  startedAt: string;
  completedAt: string;
  durationMs: number;

  // Inputs
  contextHealthScore: number;
  performanceScore: number;
  readinessScore: number;

  // Outputs
  hypothesesGenerated: number;
  hypothesesSelected: number;
  experimentsCreated: number;
  optimizationsApplied: number;
  updatesProposed: number;
  updatesApplied: number;

  // Changes
  budgetChanges: BudgetChange[];
  creativeChanges: CreativeRecommendation[];
  audienceChanges: TargetingChange[];

  // Signals
  signalsDetected: number;
  alertsTriggered: number;

  // Summary
  summary: string;
  highlights: string[];
  concerns: string[];
  nextActions: string[];

  // Status
  status: 'success' | 'partial' | 'failed' | 'skipped';
  errorMessage?: string;

  // Governance
  autonomyLevel: AutonomyLevel;
  humanOverrides: number;
}

/**
 * Autopilot log entry
 */
export interface AutopilotLogEntry {
  id: string;
  companyId: string;
  timestamp: string;

  action: AutopilotAction;
  category: 'hypothesis' | 'experiment' | 'optimization' | 'signal' | 'cycle' | 'override' | 'error';

  description: string;
  details: Record<string, unknown>;

  // Attribution
  triggeredBy: 'autopilot' | 'human' | 'signal' | 'schedule';
  userId?: string;

  // Impact
  impactedDomains: DomainName[];
  impactedFields: string[];

  // Outcome
  outcome: 'success' | 'failure' | 'pending' | 'cancelled';
  outcomeDetails?: string;
}

export type AutopilotAction =
  | 'cycle_started'
  | 'cycle_completed'
  | 'hypothesis_generated'
  | 'hypothesis_validated'
  | 'experiment_created'
  | 'experiment_started'
  | 'experiment_completed'
  | 'budget_reallocated'
  | 'creative_optimized'
  | 'audience_refined'
  | 'signal_detected'
  | 'alert_triggered'
  | 'emergency_stop'
  | 'human_override'
  | 'config_changed'
  | 'quarter_plan_generated';

// ============================================================================
// Strategy Score Types
// ============================================================================

/**
 * Overall strategy score for a company
 */
export interface StrategyScore {
  companyId: string;
  calculatedAt: string;

  // Overall
  overall: number; // 0-100
  trend: 'improving' | 'stable' | 'declining';

  // Components
  components: {
    performanceVsKpis: number;
    forecastAccuracy: number;
    creativeFreshness: number;
    audiencePenetration: number;
    conversionQuality: number;
    seasonalityAlignment: number;
    governanceHealth: number;
    contextHealth: number;
  };

  // Weights used
  weights: Record<string, number>;

  // Insights
  strengths: string[];
  weaknesses: string[];
  opportunities: string[];
  threats: string[];

  // Recommendations
  topRecommendations: string[];
}
