'use client';

// app/c/[companyId]/media/program/MediaProgramClient.tsx
// Client component for Media Program page
//
// Modes:
// - "review-activate": Program was created from Media Lab plan (shows review UI)
// - "manual": Direct setup without Media Lab (shows manual setup form)
// - "dashboard": Program already exists and is active (shows dashboard)

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { MediaDashboard, MediaProgramSetup } from '@/components/media/dashboard';
import type { MediaProgram } from '@/lib/media/programs';
import type { MediaPlan } from '@/lib/types/mediaLab';

interface MediaProgramClientProps {
  companyId: string;
  companyName: string;
  initialProgram: MediaProgram | null;
  mode: 'review-activate' | 'manual' | 'dashboard';
  sourcePlan?: MediaPlan | null;
}

export function MediaProgramClient({
  companyId,
  companyName,
  initialProgram,
  mode,
  sourcePlan,
}: MediaProgramClientProps) {
  const router = useRouter();
  const [program, setProgram] = useState<MediaProgram | null>(initialProgram);
  const [isEditing, setIsEditing] = useState(false);
  const [isActivating, setIsActivating] = useState(false);

  const handleProgramCreated = useCallback((newProgram: MediaProgram) => {
    setProgram(newProgram);
    // Redirect to media tab to see the new program
    router.push(`/c/${companyId}/media`);
    router.refresh();
  }, [companyId, router]);

  const handleEditProgram = useCallback(() => {
    setIsEditing(true);
  }, []);

  const handleActivateProgram = useCallback(async () => {
    if (!program) return;

    setIsActivating(true);
    try {
      const res = await fetch(`/api/media/programs/${companyId}/${program.id}/activate`, {
        method: 'POST',
      });

      if (!res.ok) {
        throw new Error('Failed to activate program');
      }

      // Redirect to media tab
      router.push(`/c/${companyId}/media`);
      router.refresh();
    } catch (error) {
      console.error('Failed to activate program:', error);
      setIsActivating(false);
    }
  }, [companyId, program, router]);

  // Dashboard mode - program is active
  if (mode === 'dashboard' && program) {
    return (
      <MediaDashboard
        companyId={companyId}
        companyName={companyName}
        program={program}
        onEditProgram={handleEditProgram}
      />
    );
  }

  // Review & Activate mode - program created from Media Lab
  if (mode === 'review-activate' && program) {
    return (
      <div className="max-w-2xl mx-auto">
        {/* Header with AI badge */}
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-2">
            <h2 className="text-xl font-semibold text-slate-100">Review & Activate Media Program</h2>
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-amber-500/10 border border-amber-500/30 text-amber-400 text-[10px] font-medium">
              <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
              From Media Lab
            </span>
          </div>
          <p className="text-sm text-slate-400">
            This program was generated by Media Lab{sourcePlan ? ` from "${sourcePlan.name}"` : ''}.
            Review the channels and budgets below, then activate to start tracking.
          </p>
        </div>

        {/* Program Summary Card */}
        <div className="rounded-xl border border-slate-800 bg-slate-900/50 p-5 mb-6">
          <div className="flex items-start justify-between mb-4">
            <div>
              <h3 className="text-lg font-medium text-slate-200">{program.name}</h3>
              <p className="text-xs text-slate-500 mt-0.5">
                {program.channels.filter(c => c.isActive).length} channels •{' '}
                ${program.totalMonthlyBudget.toLocaleString()}/mo budget
              </p>
            </div>
            <span className="px-2 py-1 rounded text-xs font-medium bg-blue-500/10 text-blue-400 border border-blue-500/30">
              Draft
            </span>
          </div>

          {/* Channel List */}
          <div className="space-y-2 mb-4">
            <p className="text-[10px] text-slate-500 uppercase tracking-wide">Channels</p>
            <div className="grid gap-2">
              {program.channels.filter(c => c.isActive).map((channel) => (
                <div
                  key={channel.channel}
                  className="flex items-center justify-between p-3 rounded-lg bg-slate-800/50 border border-slate-700/50"
                >
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium text-slate-300 capitalize">
                      {channel.channel}
                    </span>
                    {channel.provider && (
                      <span className="text-[10px] text-slate-500">
                        via {channel.provider.replace('_', ' ')}
                      </span>
                    )}
                  </div>
                  <span className="text-sm font-medium text-slate-200 tabular-nums">
                    ${(channel.monthlyBudget || 0).toLocaleString()}/mo
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Source Plan Link */}
          {sourcePlan && (
            <div className="pt-4 border-t border-slate-700/50">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500">Source Plan</span>
                <Link
                  href={`/c/${companyId}/diagnostics/media?plan=${sourcePlan.id}`}
                  className="text-xs text-blue-400 hover:text-blue-300"
                >
                  {sourcePlan.name} →
                </Link>
              </div>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex items-center gap-3">
          <button
            onClick={handleActivateProgram}
            disabled={isActivating}
            className="flex-1 px-4 py-2.5 text-sm font-medium bg-amber-500 text-slate-900 rounded-lg hover:bg-amber-400 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isActivating ? 'Activating...' : 'Activate Media Program'}
          </button>
          <Link
            href={`/c/${companyId}/diagnostics/media`}
            className="px-4 py-2.5 text-sm font-medium text-slate-400 hover:text-slate-300 transition-colors"
          >
            Back to Media Lab
          </Link>
        </div>
      </div>
    );
  }

  // Manual mode - show setup form (also fallback for review-activate without program)
  return (
    <MediaProgramSetup
      companyId={companyId}
      companyName={companyName}
      onComplete={handleProgramCreated}
    />
  );
}
