// lib/types/companyNarrative.ts
// Company Status Narrative types for AI-generated summaries
//
// This module defines types for the AI-generated narrative that powers
// the "Here's where we are / what's working / what's not" sections
// on the Company Overview page.

/**
 * AI-generated narrative for company status
 *
 * This is generated from CompanyStatusSummary, CompanyAnalyticsSnapshot,
 * and optionally existing findings. Used to provide human-readable
 * context in the Status View.
 */
export interface CompanyStatusNarrative {
  /** 2-3 sentence overview of company status */
  summary: string;

  /** Bullet-like strings highlighting strengths/wins */
  whatsWorking: string[];

  /** Bullet-like strings highlighting weaknesses/risks */
  whatsNotWorking: string[];

  /** 3-5 priority focus bullets for next 30-90 days */
  priorityFocus: string[];

  /** When this narrative was generated (ISO) */
  updatedAt: string;

  /** Whether this was generated by AI or is a fallback */
  isAiGenerated?: boolean;

  /** Model used for generation (for debugging) */
  modelUsed?: string;
}

/**
 * Default empty narrative for use when AI generation fails or isn't needed
 */
export function getEmptyNarrative(): CompanyStatusNarrative {
  return {
    summary: '',
    whatsWorking: [],
    whatsNotWorking: [],
    priorityFocus: [],
    updatedAt: new Date().toISOString(),
    isAiGenerated: false,
  };
}

/**
 * Fallback narrative for companies without sufficient data
 */
export function getFallbackNarrative(reason: 'no_analytics' | 'no_data' | 'error'): CompanyStatusNarrative {
  const narratives: Record<string, CompanyStatusNarrative> = {
    no_analytics: {
      summary:
        'We do not yet have enough analytics or diagnostic data to describe this company\'s performance in detail. Connect analytics integrations to establish a performance baseline.',
      whatsWorking: [],
      whatsNotWorking: [],
      priorityFocus: [
        'Connect analytics (GA4, Search Console) to establish a performance baseline.',
        'Run a full GAP assessment to understand strengths and gaps.',
        'Review existing brand and website assets for quick wins.',
      ],
      updatedAt: new Date().toISOString(),
      isAiGenerated: false,
    },
    no_data: {
      summary:
        'This company has limited data available. Complete the initial discovery process to unlock detailed insights.',
      whatsWorking: [],
      whatsNotWorking: [],
      priorityFocus: [
        'Complete company onboarding and data collection.',
        'Connect available integrations (analytics, CRM).',
        'Schedule discovery call to understand business goals.',
      ],
      updatedAt: new Date().toISOString(),
      isAiGenerated: false,
    },
    error: {
      summary:
        'There was an issue generating a detailed narrative. Review the latest GAP assessment and analytics data manually.',
      whatsWorking: [],
      whatsNotWorking: [],
      priorityFocus: [],
      updatedAt: new Date().toISOString(),
      isAiGenerated: false,
    },
  };

  return narratives[reason] || narratives.error;
}
