// lib/types/strategyOrchestration.ts
// Strategy Orchestration Types
//
// Defines the complete type system for the AI-first strategy workflow:
// Objectives -> Strategy -> Tactics
//
// KEY PRINCIPLES:
// - AI writes DRAFTS only until user applies
// - No silent fallbacks - explicit states for everything
// - Provenance tracking for all AI-generated content
// - Freshness hashes to detect stale data

import type {
  StrategyObjective,
  StrategyPillar,
  StrategyPlay,
  TacticChannel,
  ImpactLevel,
  EffortLevel,
  ConfidenceLevel,
} from './strategy';

// ============================================================================
// Freshness Hashes (for staleness detection)
// ============================================================================

/**
 * Freshness hashes for detecting when upstream data has changed
 * Used to show "stale" banners in the UI
 */
export interface FreshnessHashes {
  /** Hash of context data used for strategy generation */
  contextHash: string;
  /** Hash of objectives (triggers strategy refresh) */
  objectivesHash: string;
  /** Hash of strategy (triggers tactics refresh) */
  strategyHash: string;
  /** Hash of strategy when current tactics were derived */
  tacticsDerivedFromStrategyHash: string | null;
}

/**
 * Compute a simple hash from an object
 */
export function computeHash(data: unknown): string {
  const str = JSON.stringify(data);
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return Math.abs(hash).toString(36);
}

// ============================================================================
// Provenance (tracking AI-generated content)
// ============================================================================

/**
 * Provenance metadata for AI-generated content
 */
export interface AIProvenance {
  /** Whether this content was generated by AI */
  generatedByAI: boolean;
  /** When the content was generated */
  generatedAt: string;
  /** Hashes of inputs used for generation */
  basedOnHashes: {
    contextHash?: string;
    objectivesHash?: string;
    strategyHash?: string;
  };
  /** Model used for generation */
  model?: string;
  /** Confidence level of the generation */
  confidence?: ConfidenceLevel;
}

// ============================================================================
// Context Snapshot (read-only facts for AI input)
// ============================================================================

/**
 * Snapshot of context facts for strategy generation
 * This is a READ-ONLY view - Context is never modified by Strategy
 */
export interface ContextSnapshot {
  /** Company identifier */
  companyId: string;
  /** Company name */
  companyName: string;

  // Audience facts
  audience: {
    primaryAudience: string | null;
    icpDescription: string | null;
    segments: string[] | null;
  };

  // Offering facts
  offering: {
    primaryProducts: string[] | null;
    valueProposition: string | null;
    heroProducts: string[] | null;
  };

  // Constraints facts
  constraints: {
    minBudget: number | null;
    maxBudget: number | null;
    budgetNotes: string | null;
    geographicConstraints: string | null;
    complianceRequirements: string[] | null;
  };

  // Competition summary
  competition: {
    competitors: Array<{
      name: string;
      description: string | null;
      isB2C: boolean | null;
    }>;
    competitivePosition: string | null;
  };

  // Brand facts
  brand: {
    positioning: string | null;
    voiceTone: string | null;
    coreValues: string[] | null;
  };

  // Hash for staleness detection
  hash: string;
}

// ============================================================================
// Objectives
// ============================================================================

/**
 * Strategy objective with status tracking
 */
export interface OrchestrationObjective extends StrategyObjective {
  /** Status of this objective */
  status: 'draft' | 'active' | 'achieved' | 'deferred' | 'abandoned';
  /** When the objective was last updated */
  updatedAt: string;
  /** Provenance if AI-generated */
  provenance?: AIProvenance;
}

/**
 * Draft objective from AI proposal
 */
export interface ObjectiveDraft {
  text: string;
  metric?: string;
  target?: string;
  timeframe?: string;
  rationale: string;
  confidence: ConfidenceLevel;
}

// ============================================================================
// Strategy
// ============================================================================

/**
 * Strategic priority with provenance
 */
export interface OrchestrationPriority extends StrategyPillar {
  /** Provenance if AI-generated */
  provenance?: AIProvenance;
  /** Which objectives this priority supports */
  objectiveIds?: string[];
}

/**
 * Draft strategy from AI proposal
 */
export interface StrategyDraft {
  title: string;
  summary: string;

  /** Strategic priorities */
  priorities: Array<{
    title: string;
    description: string;
    rationale: string;
    tradeoff: string;
    priority: 'high' | 'medium' | 'low';
    objectiveIds?: string[];
    confidence: ConfidenceLevel;
  }>;

  /** Explicit tradeoffs */
  tradeoffs: {
    optimizesFor: string[];
    sacrifices: string[];
    risks: string[];
  };

  /** AI's rationale for this strategy */
  rationale: string;

  /** Assumptions made by the AI */
  assumptions: string[];

  /** Overall confidence */
  confidence: ConfidenceLevel;

  /** Alignment notes - how this connects to objectives */
  alignmentNotes: string;
}

// ============================================================================
// Tactics
// ============================================================================

/**
 * Tactical play with provenance
 */
export interface OrchestrationTactic extends StrategyPlay {
  /** Provenance if AI-generated */
  provenance?: AIProvenance;
  /** Hash of strategy this tactic was derived from */
  derivedFromStrategyHash?: string;
}

/**
 * Draft tactic from AI proposal
 */
export interface TacticDraft {
  title: string;
  description: string;

  /** Which objectives this tactic supports */
  objectiveIds: string[];
  /** Which priorities this tactic implements */
  priorityIds: string[];

  /** Channel tags */
  channels: TacticChannel[];

  /** Impact/effort estimates */
  impact: ImpactLevel;
  effort: EffortLevel;

  /** Success metric */
  successMetric?: string;

  /** Timeframe */
  timeframe?: string;

  /** AI's rationale */
  rationale: string;

  /** How this tactic aligns with strategy */
  alignmentNote: string;

  /** Confidence level */
  confidence: ConfidenceLevel;
}

// ============================================================================
// Strategy View Model
// ============================================================================

/**
 * Complete strategy view model - SINGLE SOURCE OF TRUTH for UI
 */
export interface StrategyOrchestrationViewModel {
  /** Company identifier */
  companyId: string;
  /** Company name */
  companyName: string;

  // Context snapshot (read-only facts)
  contextSnapshot: ContextSnapshot;

  // Objectives
  objectives: OrchestrationObjective[];

  // Strategies (multi-strategy support)
  strategies: Array<{
    id: string;
    title: string;
    status: 'draft' | 'finalized' | 'archived';
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
  }>;
  activeStrategyId: string | null;

  // Active strategy details
  activeStrategy: {
    id: string;
    title: string;
    summary: string;
    priorities: OrchestrationPriority[];
    tradeoffs: {
      optimizesFor: string[];
      sacrifices: string[];
      risks: string[];
    };
    status: 'draft' | 'finalized' | 'archived';
    provenance?: AIProvenance;
  } | null;

  // Tactics (scoped to active strategy)
  tactics: OrchestrationTactic[];

  // Readiness
  readiness: {
    completenessPercent: number;
    missingInputs: Array<{
      field: string;
      label: string;
      critical: boolean;
    }>;
    canGenerateStrategy: boolean;
    canGenerateTactics: boolean;
    blockedReason: string | null;
  };

  // Freshness hashes for staleness detection
  hashes: FreshnessHashes;

  // Staleness indicators
  staleness: {
    /** Strategy may be stale because objectives changed */
    strategyStale: boolean;
    strategyStaleReason: string | null;
    /** Tactics may be stale because strategy changed */
    tacticsStale: boolean;
    tacticsStaleReason: string | null;
    /** Context changed since last generation */
    contextChanged: boolean;
    contextChangedReason: string | null;
  };

  // Metadata
  meta: {
    resolvedAt: string;
    viewModelVersion: string;
  };
}

// ============================================================================
// AI Proposal Actions
// ============================================================================

/**
 * Actions supported by the AI propose endpoint
 */
export type AIProposalAction =
  | 'propose_objectives'
  | 'propose_strategy'
  | 'propose_tactics'
  | 'improve_field';

/**
 * Request to AI propose endpoint
 */
export interface AIProposalRequest {
  action: AIProposalAction;

  /** Strategy ID to operate on (uses active if not provided) */
  strategyId?: string;

  /** For improve_field action - which field to improve */
  fieldPath?: string;

  /** For improve_field action - current value to improve */
  currentValue?: unknown;

  /** Additional context/instructions */
  instructions?: string;
}

/**
 * Response from AI propose endpoint
 */
export interface AIProposalResponse {
  /** Action that was performed */
  action: AIProposalAction;

  /** When the proposal was generated */
  proposedAt: string;

  /** Objective drafts (for propose_objectives) */
  objectiveDrafts?: ObjectiveDraft[];

  /** Strategy draft (for propose_strategy) */
  strategyDraft?: StrategyDraft;

  /** Tactic drafts (for propose_tactics) */
  tacticDrafts?: TacticDraft[];

  /** Field improvement (for improve_field) */
  fieldImprovement?: {
    fieldPath: string;
    originalValue: unknown;
    improvedValue: unknown;
    rationale: string;
    diff?: string;
  };

  /** Inputs that were used for generation */
  inputsUsed: string[];

  /** Hashes of inputs at generation time */
  inputHashes: {
    contextHash: string;
    objectivesHash: string;
    strategyHash: string | null;
  };

  /** Overall confidence */
  confidence: ConfidenceLevel;

  /** Warnings or notes */
  warnings?: string[];

  /** IMPORTANT: These are always true for AI proposals */
  isDraft: true;
  requiresApproval: true;
}

// ============================================================================
// Apply Actions
// ============================================================================

/**
 * Request to apply strategy draft
 */
export interface ApplyStrategyDraftRequest {
  companyId: string;
  strategyId?: string; // If updating existing
  draft: StrategyDraft;
  inputHashes: {
    contextHash: string;
    objectivesHash: string;
  };
}

/**
 * Request to apply tactic drafts
 */
export interface ApplyTacticsDraftRequest {
  companyId: string;
  strategyId: string;
  drafts: TacticDraft[];
  inputHashes: {
    contextHash: string;
    strategyHash: string;
  };
}

/**
 * Request to apply objective drafts
 */
export interface ApplyObjectivesDraftRequest {
  companyId: string;
  strategyId: string;
  drafts: ObjectiveDraft[];
  inputHashes: {
    contextHash: string;
  };
}

/**
 * Response from apply endpoint
 */
export interface ApplyDraftResponse {
  success: boolean;

  /** IDs of created/updated items */
  createdIds?: string[];
  updatedIds?: string[];

  /** The updated strategy (if applicable) */
  strategy?: {
    id: string;
    title: string;
    updatedAt: string;
  };

  /** Error if failed */
  error?: string;
}

// ============================================================================
// UI State Types
// ============================================================================

/**
 * State of a draft being previewed
 */
export interface DraftPreviewState {
  /** Type of draft being previewed */
  type: 'objectives' | 'strategy' | 'tactics' | 'field';

  /** The draft content */
  draft: ObjectiveDraft[] | StrategyDraft | TacticDraft[] | {
    fieldPath: string;
    originalValue: unknown;
    improvedValue: unknown;
    rationale: string;
  };

  /** Input hashes at generation time */
  inputHashes: {
    contextHash: string;
    objectivesHash: string;
    strategyHash: string | null;
  };

  /** Whether the draft is being applied */
  isApplying: boolean;
}

/**
 * Staleness banner configuration
 */
export interface StalenessBanner {
  type: 'strategy' | 'tactics' | 'context';
  message: string;
  action: {
    label: string;
    onClick: () => void;
  };
}
